package project;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static project.UrgencyQuery.ticket_id;
import static project.UrgencyQuery.tickets;

/**
 * @author IK
 */

public class Search extends javax.swing.JDialog {
      Connection con;
      ResultSet rs;
      PreparedStatement stat;


      static  String ticket_id, urgency, name, phone,address, product_details, complaint, email;
      static ArrayList<String> urgency_result=new ArrayList<String>();
      static int row_count;
    /**
     * Creates new form Search
     * @param parent
     * @param modal
     */

    public Search(java.awt.Frame parent, boolean modal) {
       super(parent, modal);
       initComponents();
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents

    private void initComponents() {



        jPanel2 = new javax.swing.JPanel();

        jLabel1 = new javax.swing.JLabel();

        jLabel14 = new javax.swing.JLabel();

        jPanel4 = new javax.swing.JPanel();

        jLabel11 = new javax.swing.JLabel();

        jTextField1 = new javax.swing.JTextField();

        jLabel12 = new javax.swing.JLabel();

        jComboBox1 = new javax.swing.JComboBox<>();

        jLabel2 = new javax.swing.JLabel();

        jPanel3 = new javax.swing.JPanel();

        searchButton = new javax.swing.JButton();



        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        setLocation(new java.awt.Point(550, 250));

        setResizable(false);

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());



        jPanel2.setBackground(new java.awt.Color(0, 0, 81));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());



        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Search");

        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 4, -1, 50));



        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/imgs/Search-icon.png"))); // NOI18N

        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, -10, 120, 70));



        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 780, 60));



        jPanel4.setBackground(new java.awt.Color(51, 255, 255));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());



        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel11.setText("Search By Ticket ID:");

        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 200, -1));



        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {

                jTextField1MouseClicked(evt);

            }

        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jTextField1ActionPerformed(evt);

            }

        });

        jPanel4.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 120, -1));



        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel12.setText("Search By Priority:");

        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 190, -1));



        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "High", "Mediuim", "Low" }));

        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {

                jComboBox1MouseClicked(evt);

            }

        });

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jComboBox1ActionPerformed(evt);

            }

        });

        jPanel4.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, -1, -1));



        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jLabel2.setText("OR");

        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 60, 40));



        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 780, 190));



        jPanel3.setBackground(new java.awt.Color(0, 0, 81));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());



        searchButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        searchButton.setText("Search");

        searchButton.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                searchButtonActionPerformed(evt);

            }

        });

        jPanel3.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 11, 140, 40));



        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 780, 60));



        pack();

    }// </editor-fold>//GEN-END:initComponents

        public void displayTickets(){
        int rows = tickets.size();
           JPanel ticketPriorityPanel = new JPanel();
           ticketPriorityPanel.setPreferredSize(new Dimension(400,200));
           ticketPriorityPanel.setLayout(new GridLayout(0, 2)); 
          

          for(int i=0; i < tickets.size();i++){
         
          // variabe to be used  in actionPerformed for 'view' button
          String id =  tickets.get(i);
         JLabel tickLabel = new JLabel(tickets.get(i),JLabel.CENTER);
          tickLabel.setBorder(BorderFactory.createLineBorder(Color.black,1));
          JButton tickButton = new JButton("view");
          tickButton.setBorder(BorderFactory.createLineBorder(Color.black, 1 ));
          ticketPriorityPanel.add(tickLabel);
          ticketPriorityPanel.add(tickButton);
          tickButton.addActionListener(new ActionListener(){

             public void actionPerformed(ActionEvent e){
                   try {                        
                  Class.forName("com.mysql.jdbc.Driver");
                  con = DriverManager.getConnection("jdbc:mysql:///logger", "root", "") ;                  
                  stat = con.prepareStatement("SELECT * FROM  tickets  WHERE ticket_id =?");
                  ticket_id = id;
                  stat.setString(1,ticket_id);
                  rs = stat.executeQuery();   

                 //save the details to their corresponding static variables
                if(rs.next()){
                ticket_id = rs.getString("ticket_id");
                 name = rs.getString("name");
                 phone = rs.getString("phone");
                 address = rs.getString("address");
                 email = rs.getString("email");
                 product_details = rs.getString("details");
                 complaint = rs.getString("complaint");
                 urgency = rs.getString("urgency");

//                 //alert the user that the ticket was found
//                 JOptionPane.showMessageDialog(new JDialog(),"Ticket "+ ticket_id +" Found \n  View Details", "Ticket Found", JOptionPane.INFORMATION_MESSAGE);
//                 
                 // Open the dialog to display the details of the ticket ID selected
                 TicketDetails t = new TicketDetails(name, address, email, phone, product_details, complaint, urgency);

                 t.setVisible(true);
                    }

                //if ticket was not found
                else{
                JOptionPane.showMessageDialog(new JDialog(),"Ticket "+ ticket_id +" Does Not Exist", "Ticket Not Found", JOptionPane.ERROR_MESSAGE);
                }
                
            }

            catch (SQLException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(new JDialog(),"Ticket "+ ticket_id + ex, "Ticket Error", JOptionPane.ERROR_MESSAGE);
            } 
            catch (ClassNotFoundException ex) {
                Logger.getLogger(Search.class.getName()).log(Level.SEVERE, null, ex);
                  }
              }
          });
 

        }

        JDialog tk = new JDialog();
        tk.setTitle("Search Details");
        tk.setLocation(100, 150);
        
        tk.setSize(400,400);
        tk.setContentPane(ticketPriorityPanel);
        tk.setVisible(true);
        tk.setModal(false);
        tk.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        

    }
  

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
            //get the user's input
            ticket_id = jTextField1.getText();
            urgency =(String) jComboBox1.getSelectedItem();
            
          

            //i the user has no selected any input 
            if (ticket_id.equals("")  &&  urgency.equals(" ")){
               JOptionPane.showMessageDialog(this,"both fields cannot be left blank \n Choose a search method ", "Ticket Error", JOptionPane.ERROR_MESSAGE);
            }
             else

                //if the user has inputed a ticket ID
                if (!ticket_id.equals("")) {

             try {                        
                  Class.forName("com.mysql.jdbc.Driver");
                  con = DriverManager.getConnection("jdbc:mysql:///logger", "root", "") ;                  
                  stat = con.prepareStatement("SELECT * FROM  tickets  WHERE ticket_id =?");
                  stat.setString(1,ticket_id);
                  rs = stat.executeQuery();   

                  //save the details to their corresponding static variables
                 if(rs.next()){
                 ticket_id = rs.getString("ticket_id");
                 name = rs.getString("name");
                 phone = rs.getString("phone");
                 address = rs.getString("address");
                 email = rs.getString("email");
                 product_details = rs.getString("details");
                 complaint = rs.getString("complaint");
                 urgency = rs.getString("urgency");
     

                 //alert the user that the ticket was found
//                 JOptionPane.showMessageDialog(this,"Ticket "+ ticket_id +" Found \n  View Details", "Ticket Found", JOptionPane.INFORMATION_MESSAGE);
            // Open the dialog to display the details of the ticket ID selected

                 TicketDetails t = new TicketDetails(name, address, email, phone, product_details, complaint, urgency);
                 t.setVisible(true);
                  }

                //if ticket was not found
                else{
                JOptionPane.showMessageDialog(this,"Ticket "+ ticket_id +" Does Not Exist", "Ticket Not Found", JOptionPane.INFORMATION_MESSAGE);
                } 
           }

          catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog(this,"Ticket "+ ticket_id +e, "Ticket Error", JOptionPane.ERROR_MESSAGE);
            }

          catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,"Ticket "+ ticket_id + ex, "Ticket Error", JOptionPane.ERROR_MESSAGE);
            }          

          }

            // else if search by urgency is selected
              else {
                if(!urgency.equals("select") ){
                urgency  = (String) jComboBox1.getSelectedItem(); 
                                        tickets.clear();

                              try {                        
                  Class.forName("com.mysql.jdbc.Driver");
                  con = DriverManager.getConnection("jdbc:mysql:///logger", "root", "") ;                  
                  stat = con.prepareStatement("SELECT ticket_id FROM `tickets` WHERE urgency = ? ");
                  stat.setString(1,urgency);
                  rs = stat.executeQuery();   
                                                                       
                    if (rs.next()){
                  
                    while(rs.next()){
                        ticket_id = rs.getString("ticket_id");
                        tickets.add(ticket_id);
                        System.out.println(ticket_id);
                     }

 

                 //alert the user that the ticket was found
                //                 JOptionPane.showMessageDialog(new JDialog(),"Tickets  Found \n  View Details", "Ticket Found", JOptionPane.INFORMATION_MESSAGE);
                                  
                }

                 else{
                JOptionPane.showMessageDialog(new JDialog(),"Ticket Does Not Exist", "No Ticket Not Found", JOptionPane.INFORMATION_MESSAGE);
                }

               }  //end try

               catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(new JDialog(),"Ticket "+ ticket_id + ex, "Ticket Error", JOptionPane.ERROR_MESSAGE);
            }
             catch (ClassNotFoundException ex) {        
                 Logger.getLogger(Search.class.getName()).log(Level.SEVERE, null, ex);
                    }

                displayTickets();
                this.setVisible(false);
//                this.setModal(false);
    }//GEN-LAST:event_searchButtonActionPerformed
     }
    }

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
       jComboBox1.setSelectedIndex(0);
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
       jTextField1.setText(null);
    }//GEN-LAST:event_jComboBox1MouseClicked


    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">

        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.

         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 

         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }

        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }

        //</editor-fold>
        /* Create and display the dialog */

        java.awt.EventQueue.invokeLater(new Runnable() {
           @Override
            public void run() {
                Search dialog = new Search(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });

               dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables

    private javax.swing.JComboBox<String> jComboBox1;

    private javax.swing.JLabel jLabel1;

    private javax.swing.JLabel jLabel11;

    private javax.swing.JLabel jLabel12;

    private javax.swing.JLabel jLabel14;

    private javax.swing.JLabel jLabel2;

    private javax.swing.JPanel jPanel2;

    private javax.swing.JPanel jPanel3;

    private javax.swing.JPanel jPanel4;

    private javax.swing.JTextField jTextField1;

    private javax.swing.JButton searchButton;

    // End of variables declaration//GEN-END:variables
}

