/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

/**
 *
 * @author IK
 */
public class TicketDetails extends javax.swing.JDialog {

    /**
     * Creates new form TicketDetails
     */
    public TicketDetails(String name, String address, String email, String phone, String details, String complaint, String urgency) {
        initComponents();
        
        this.custName.setText(name);
        this.custPhone.setText(phone);
        this.custEmail.setText(email);
        this.custAdd.setText(address);
        this.custComplaint.setText(complaint);
        this.prodDetails.setText(details);
        this.prodUrg.setText(urgency);
        this.setModal(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        custAdd = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        prodUrg = new javax.swing.JLabel();
        custName = new javax.swing.JLabel();
        custPhone = new javax.swing.JLabel();
        custEmail = new javax.swing.JLabel();
        prodDetails = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        custComplaint = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(700, 200));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        custAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        custAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        custAdd.setText(Search.address);
        jPanel1.add(custAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 680, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Urgency:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 90, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Customer Name:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 160, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Customer Phone:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 160, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Product Details:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 160, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Customer Complaint:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 190, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Customer E-mail:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 160, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Customer Address:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 180, -1));

        prodUrg.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        prodUrg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prodUrg.setText(Search.urgency);
        jPanel1.add(prodUrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 680, 30));

        custName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        custName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        custName.setText(Search.name);
        jPanel1.add(custName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 680, 30));

        custPhone.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        custPhone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        custPhone.setText(Search.phone);
        jPanel1.add(custPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 680, 30));

        custEmail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        custEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        custEmail.setText(Search.email);
        jPanel1.add(custEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 680, 30));

        prodDetails.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        prodDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prodDetails.setText(Search.product_details);
        jPanel1.add(prodDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 680, 30));

        custComplaint.setEditable(false);
        custComplaint.setColumns(15);
        custComplaint.setLineWrap(true);
        custComplaint.setRows(5);
        custComplaint.setWrapStyleWord(true);
        jScrollPane1.setViewportView(custComplaint);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 340, 120));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 910, 470));

        jPanel2.setBackground(new java.awt.Color(0, 0, 81));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(Search.ticket_id);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ticket Details");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ticket ID");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/imgs/gpk-log-icon.png"))); // NOI18N
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, -10, 130, 130));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 110));

        jPanel3.setBackground(new java.awt.Color(0, 0, 81));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 910, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel custAdd;
    private javax.swing.JTextArea custComplaint;
    private javax.swing.JLabel custEmail;
    private javax.swing.JLabel custName;
    private javax.swing.JLabel custPhone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel prodDetails;
    private javax.swing.JLabel prodUrg;
    // End of variables declaration//GEN-END:variables
}
